
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * The CLASS web service provides processing of eCLASS and iCLASS queries.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClassWebServiceImpl", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://cadataivv.ca.state.sbu/CLASSWS/Class.asmx?wsdl")
public class ClassWebServiceImpl
    extends Service
{

    private final static URL CLASSWEBSERVICEIMPL_WSDL_LOCATION;
    private final static WebServiceException CLASSWEBSERVICEIMPL_EXCEPTION;
    private final static QName CLASSWEBSERVICEIMPL_QNAME = new QName("http://tempuri.org/", "ClassWebServiceImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://cadataivv.ca.state.sbu/CLASSWS/Class.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLASSWEBSERVICEIMPL_WSDL_LOCATION = url;
        CLASSWEBSERVICEIMPL_EXCEPTION = e;
    }

    public ClassWebServiceImpl() {
        super(__getWsdlLocation(), CLASSWEBSERVICEIMPL_QNAME);
    }

    public ClassWebServiceImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLASSWEBSERVICEIMPL_QNAME, features);
    }

    public ClassWebServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, CLASSWEBSERVICEIMPL_QNAME);
    }

    public ClassWebServiceImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLASSWEBSERVICEIMPL_QNAME, features);
    }

    public ClassWebServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClassWebServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClassWebServiceImplSoap
     */
    @WebEndpoint(name = "ClassWebServiceImplSoap")
    public ClassWebServiceImplSoap getClassWebServiceImplSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ClassWebServiceImplSoap"), ClassWebServiceImplSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClassWebServiceImplSoap
     */
    @WebEndpoint(name = "ClassWebServiceImplSoap")
    public ClassWebServiceImplSoap getClassWebServiceImplSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ClassWebServiceImplSoap"), ClassWebServiceImplSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLASSWEBSERVICEIMPL_EXCEPTION!= null) {
            throw CLASSWEBSERVICEIMPL_EXCEPTION;
        }
        return CLASSWEBSERVICEIMPL_WSDL_LOCATION;
    }

}
