
package ca932631;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "iCLASSSoap", targetNamespace = "http://ca932631")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICLASSSoap {


    /**
     * This Web method allows a client application to send CCD Person Finder queries to iCLASS.
     * 
     * @param mErrorMessage
     * @param mResponseState
     * @param xmlString
     * @param submitXMLResult
     */
    @WebMethod(operationName = "SubmitXML", action = "http://ca932631/SubmitXML")
    @RequestWrapper(localName = "SubmitXML", targetNamespace = "http://ca932631", className = "ca932631.SubmitXML")
    @ResponseWrapper(localName = "SubmitXMLResponse", targetNamespace = "http://ca932631", className = "ca932631.SubmitXMLResponse")
    public void submitXML(
        @WebParam(name = "xmlString", targetNamespace = "http://ca932631")
        String xmlString,
        @WebParam(name = "SubmitXMLResult", targetNamespace = "http://ca932631", mode = WebParam.Mode.OUT)
        Holder<String> submitXMLResult,
        @WebParam(name = "m_responseState", targetNamespace = "http://ca932631", mode = WebParam.Mode.OUT)
        Holder<Integer> mResponseState,
        @WebParam(name = "m_errorMessage", targetNamespace = "http://ca932631", mode = WebParam.Mode.OUT)
        Holder<String> mErrorMessage);

}
