
package ca932631;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * The iCLASS web service provides processing of CCD Person Finder queries.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "iCLASS", targetNamespace = "http://ca932631", wsdlLocation = "http://10.48.196.45/classws/iclass.asmx?wsdl")
public class ICLASS
    extends Service
{

    private final static URL ICLASS_WSDL_LOCATION;
    private final static WebServiceException ICLASS_EXCEPTION;
    private final static QName ICLASS_QNAME = new QName("http://ca932631", "iCLASS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.48.196.45/classws/iclass.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ICLASS_WSDL_LOCATION = url;
        ICLASS_EXCEPTION = e;
    }

    public ICLASS() {
        super(__getWsdlLocation(), ICLASS_QNAME);
    }

    public ICLASS(WebServiceFeature... features) {
        super(__getWsdlLocation(), ICLASS_QNAME, features);
    }

    public ICLASS(URL wsdlLocation) {
        super(wsdlLocation, ICLASS_QNAME);
    }

    public ICLASS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ICLASS_QNAME, features);
    }

    public ICLASS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ICLASS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICLASSSoap
     */
    @WebEndpoint(name = "iCLASSSoap")
    public ICLASSSoap getICLASSSoap() {
        return super.getPort(new QName("http://ca932631", "iCLASSSoap"), ICLASSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICLASSSoap
     */
    @WebEndpoint(name = "iCLASSSoap")
    public ICLASSSoap getICLASSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://ca932631", "iCLASSSoap"), ICLASSSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ICLASS_EXCEPTION!= null) {
            throw ICLASS_EXCEPTION;
        }
        return ICLASS_WSDL_LOCATION;
    }

}
