
package gov.state.ca.cadata.ccdws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CCDWS", targetNamespace = "http://cadata.ca.state.gov/CCDWS", wsdlLocation = "http://cadataivv.ca.state.sbu/CCDWS/CCDWS.asmx?wsdl")
public class CCDWS
    extends Service
{

    private final static URL CCDWS_WSDL_LOCATION;
    private final static WebServiceException CCDWS_EXCEPTION;
    private final static QName CCDWS_QNAME = new QName("http://cadata.ca.state.gov/CCDWS", "CCDWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://cadataivv.ca.state.sbu/CCDWS/CCDWS.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CCDWS_WSDL_LOCATION = url;
        CCDWS_EXCEPTION = e;
    }

    public CCDWS() {
        super(__getWsdlLocation(), CCDWS_QNAME);
    }

    public CCDWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), CCDWS_QNAME, features);
    }

    public CCDWS(URL wsdlLocation) {
        super(wsdlLocation, CCDWS_QNAME);
    }

    public CCDWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CCDWS_QNAME, features);
    }

    public CCDWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CCDWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CCDWSSoap
     */
    @WebEndpoint(name = "CCDWSSoap")
    public CCDWSSoap getCCDWSSoap() {
        return super.getPort(new QName("http://cadata.ca.state.gov/CCDWS", "CCDWSSoap"), CCDWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCDWSSoap
     */
    @WebEndpoint(name = "CCDWSSoap")
    public CCDWSSoap getCCDWSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://cadata.ca.state.gov/CCDWS", "CCDWSSoap"), CCDWSSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CCDWS_EXCEPTION!= null) {
            throw CCDWS_EXCEPTION;
        }
        return CCDWS_WSDL_LOCATION;
    }

}
