
package gov.state.ca.cadata.ccdws;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CCDWSSoap", targetNamespace = "http://cadata.ca.state.gov/CCDWS")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CCDWSSoap {


    /**
     * 
     * @param ccdwsQueryRequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CCDWSQuery", action = "http://cadata.ca.state.gov/CCDWS/CCDWSQuery")
    @WebResult(name = "CCDWSQueryResult", targetNamespace = "http://cadata.ca.state.gov/CCDWS")
    @RequestWrapper(localName = "CCDWSQuery", targetNamespace = "http://cadata.ca.state.gov/CCDWS", className = "gov.state.ca.cadata.ccdws.CCDWSQuery")
    @ResponseWrapper(localName = "CCDWSQueryResponse", targetNamespace = "http://cadata.ca.state.gov/CCDWS", className = "gov.state.ca.cadata.ccdws.CCDWSQueryResponse")
    public String ccdwsQuery(
        @WebParam(name = "CCDWSQueryRequest", targetNamespace = "http://cadata.ca.state.gov/CCDWS")
        String ccdwsQueryRequest);

    /**
     * 
     * @param ccdwsQueryRequestAck
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CCDWSQueryAck", action = "http://cadata.ca.state.gov/CCDWS/CCDWSQueryAck")
    @WebResult(name = "CCDWSQueryAckResult", targetNamespace = "http://cadata.ca.state.gov/CCDWS")
    @RequestWrapper(localName = "CCDWSQueryAck", targetNamespace = "http://cadata.ca.state.gov/CCDWS", className = "gov.state.ca.cadata.ccdws.CCDWSQueryAck")
    @ResponseWrapper(localName = "CCDWSQueryAckResponse", targetNamespace = "http://cadata.ca.state.gov/CCDWS", className = "gov.state.ca.cadata.ccdws.CCDWSQueryAckResponse")
    public String ccdwsQueryAck(
        @WebParam(name = "CCDWSQueryRequestAck", targetNamespace = "http://cadata.ca.state.gov/CCDWS")
        String ccdwsQueryRequestAck);

    /**
     * 
     * @param ccdwsQueryRequest
     */
    @WebMethod(operationName = "CCDWSQueryNoAck", action = "http://cadata.ca.state.gov/CCDWS/CCDWSQueryNoAck")
    @Oneway
    @RequestWrapper(localName = "CCDWSQueryNoAck", targetNamespace = "http://cadata.ca.state.gov/CCDWS", className = "gov.state.ca.cadata.ccdws.CCDWSQueryNoAck")
    public void ccdwsQueryNoAck(
        @WebParam(name = "CCDWSQueryRequest", targetNamespace = "http://cadata.ca.state.gov/CCDWS")
        String ccdwsQueryRequest);

    /**
     * 
     * @param xmlIn
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CCDWSRunPkg", action = "http://cadata.ca.state.gov/CCDWS/CCDWSRunPkg")
    @WebResult(name = "CCDWSRunPkgResult", targetNamespace = "http://cadata.ca.state.gov/CCDWS")
    @RequestWrapper(localName = "CCDWSRunPkg", targetNamespace = "http://cadata.ca.state.gov/CCDWS", className = "gov.state.ca.cadata.ccdws.CCDWSRunPkg")
    @ResponseWrapper(localName = "CCDWSRunPkgResponse", targetNamespace = "http://cadata.ca.state.gov/CCDWS", className = "gov.state.ca.cadata.ccdws.CCDWSRunPkgResponse")
    public String ccdwsRunPkg(
        @WebParam(name = "XMLIn", targetNamespace = "http://cadata.ca.state.gov/CCDWS")
        String xmlIn);

    /**
     * 
     * @param xmlIn
     */
    @WebMethod(operationName = "CCDWSRunPkgNoAck", action = "http://cadata.ca.state.gov/CCDWS/CCDWSRunPkgNoAck")
    @Oneway
    @RequestWrapper(localName = "CCDWSRunPkgNoAck", targetNamespace = "http://cadata.ca.state.gov/CCDWS", className = "gov.state.ca.cadata.ccdws.CCDWSRunPkgNoAck")
    public void ccdwsRunPkgNoAck(
        @WebParam(name = "XMLIn", targetNamespace = "http://cadata.ca.state.gov/CCDWS")
        String xmlIn);

    /**
     * 
     * @param xmlIn
     * @param byteIn
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CCDWSRunLobPkg", action = "http://cadata.ca.state.gov/CCDWS/CCDWSRunLobPkg")
    @WebResult(name = "CCDWSRunLobPkgResult", targetNamespace = "http://cadata.ca.state.gov/CCDWS")
    @RequestWrapper(localName = "CCDWSRunLobPkg", targetNamespace = "http://cadata.ca.state.gov/CCDWS", className = "gov.state.ca.cadata.ccdws.CCDWSRunLobPkg")
    @ResponseWrapper(localName = "CCDWSRunLobPkgResponse", targetNamespace = "http://cadata.ca.state.gov/CCDWS", className = "gov.state.ca.cadata.ccdws.CCDWSRunLobPkgResponse")
    public String ccdwsRunLobPkg(
        @WebParam(name = "XMLIn", targetNamespace = "http://cadata.ca.state.gov/CCDWS")
        String xmlIn,
        @WebParam(name = "byteIn", targetNamespace = "http://cadata.ca.state.gov/CCDWS")
        byte[] byteIn);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Test", action = "http://cadata.ca.state.gov/CCDWS/Test")
    @WebResult(name = "TestResult", targetNamespace = "http://cadata.ca.state.gov/CCDWS")
    @RequestWrapper(localName = "Test", targetNamespace = "http://cadata.ca.state.gov/CCDWS", className = "gov.state.ca.cadata.ccdws.Test")
    @ResponseWrapper(localName = "TestResponse", targetNamespace = "http://cadata.ca.state.gov/CCDWS", className = "gov.state.ca.cadata.ccdws.TestResponse")
    public String test();

}
